// app/inventory/_data/sample-data.js
export const sampleProducts = [
  {
    id: 1,
    nombre: 'Aceite Motor 5W-30',
    codigo: 'AM5W30001',
    categoria: 'Lubricantes',
    descripcion: 'Aceite sintético para motores de alta performance',
    unidad_medida: 'Litros',
    precio_unitario: 45.99,
    stock_minimo: 50,
    stock_actual: 120,
    ubicacion: 'Almacén A - Estante 1',
    activo: true
  },
  {
    id: 2,
    nombre: "Gasolina Premium 95",
    codigo: "GP95001",
    categoria: "Combustibles",
    descripcion: "Gasolina premium octanaje 95",
    unidad_medida: "Litros",
    precio_unitario: 1.25,
    stock_minimo: 1000,
    stock_actual: 8500,
    ubicacion: "Tanque Principal T1",
    activo: true,
  },
  {
    id: 3,
    nombre: "Diesel Ultra Bajo Azufre",
    codigo: "DUBA001",
    categoria: "Combustibles",
    descripcion: "Diesel con contenido ultra bajo de azufre",
    unidad_medida: "Litros",
    precio_unitario: 1.15,
    stock_minimo: 1500,
    stock_actual: 12000,
    ubicacion: "Tanque Principal T2",
    activo: true,
  },
  {
    id: 4,
    nombre: "Grasa Multipropósito",
    codigo: "GM001",
    categoria: "Lubricantes",
    descripcion: "Grasa para uso industrial multipropósito",
    unidad_medida: "Kilogramos",
    precio_unitario: 8.5,
    stock_minimo: 25,
    stock_actual: 15,
    ubicacion: "Almacén B - Estante 3",
    activo: true,
  },
  {
    id: 5,
    nombre: "Aditivo Anticongelante",
    codigo: "AA001",
    categoria: "Aditivos",
    descripcion: "Aditivo anticongelante para sistemas de refrigeración",
    unidad_medida: "Litros",
    precio_unitario: 12.75,
    stock_minimo: 30,
    stock_actual: 45,
    ubicacion: "Almacén A - Estante 5",
    activo: true,
  },
];